on: push
name: Test, Build and Release apk
jobs:
  build-android-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
        # channel: 'dev' # 'stable' 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter doctor
    # - run: flutter test
    - run: flutter build apk
#     - uses: actions/checkout@v2
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
#     - run: flutter build apk --debug --target-platform android-arm,android-arm64 --split-per-abi
    - run: tree build/app/outputs/apk
    - name: Upload Artifact
      continue-on-error: true
      uses: actions/upload-artifact@master
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - run: flutter build web
    - run: ls /build/web
    - name: Upload Artifact
      continue-on-error: true
      uses: actions/upload-artifact@master
      with:
        name: web.zip
        path: build/web
    # - run: sudo apt-get install libgtk-3-0 libblkid1 liblzma5
#     - run: flutter build linux --release

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build ios --release --no-codesign
#     - run: flutter build macos
    # - name: Upload Artifact
    #   continue-on-error: true
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: ios.app
    #     path: build/ios/iphoneos/Runner.app

#   windows:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: dev
# #           flutter-version: '2.5.3'
# #       - run: flutter config --enable-windows-desktop
#       - run: flutter config --enable-windows-uwp-desktop
#       - run: flutter pub get
#       - run: flutter build windows
